name: Download GIFs

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次，修改为你需要的频率

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 或你所需的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run download script
      run: python download_gif.py
